#!/bin/bash
sqlplus CONDORI/P058ad62 <<EOF
create directory backups_CONDORI as '/backups/CONDORI';
EOF

expdp CONDORI/P058ad62 DIRECTORY=backups_CONDORI LOGFILE=CONDORI.log

sqlplus CONDORI/P058ad62 <<INS

CREATE CONDORI_9:31 IDENTIFIED BY CONDORI;

GRANT CREATE SESSION TO CONDORI_9:31
INS

impdp CONDORI_9:31/P058ad62 DIRECTORY=backups_CONDORI LOGFILE=CONDORI.log

